name: cabinet
description: A new Flutter project.

dependencies:
  cloud_firestore:
  cupertino_icons: ^0.1.2
  device_info: 0.2.1
  dio: any
  firebase: ^4.3.0
  firebase_auth: ^0.5.11
  firebase_core:
  firebase_database: "^1.0.1"
  flutter:
    sdk: flutter
  google_sign_in: ^3.0.4
  http: any
  image_picker: ^0.4.4
  json: any
  mlkit: ^0.2.2
  path_provider: any
  rxdart: "^0.18.1"
  sqflite: any
  validator: "^0.0.7"
  # english_words: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is included with your application, so that you can use the icons in
  uses-material-design: true

  assets:
    - assets/images/header-profil.jpg
    - assets/images/medecin.png
    - assets/data/medecins.json
  # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
